### ISSUE TITLE
Change to other themes

### ISSUE THREAD

**Issue by little-yellow-bean** [Romko775/ng-moment-timezone-picker#33]
How can I change to other themes (e.g Bootstrap theme)

**Comment by Romko775** [comment]
Hi @little-yellow-bean!

You must write your own theme, because `ng-select` has encapsulated styles that can be only changed with `::ng-deep`

For example use 
https://github.com/Romko775/ng-moment-timezone-picker/blob/master/projects/moment-timezone-picker/assets/moment-timezone-picker.theme.scss

Cheers!
